filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Load Vundle bundle config
source ~/.vim/vundle

filetype plugin indent on

colorscheme neverland2

syntax on

set nocompatible
set modelines=0
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set updatetime=4000
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmode=list:longest
set nocursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2

set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
set wrap
set textwidth=79
set formatoptions=qrn1
set nospell

" Setup YankStack before any yank/paste keys are redefined
call yankstack#setup()

let mapleader = ","

nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

let Tlist_Use_Right_Window=1
let Tlist_WinWidth=55
set list
set listchars=tab:.\ ,eol:¬

autocmd BufLeave,FocusLost silent! wall

inoremap jj <ESC>

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk
nnoremap <C-J> <C-D>
nnoremap <C-K> <C-U>
inoremap <C-J> <C-D>
inoremap <C-K> <C-U>

" Movement between windows
nnoremap <leader>w <C-w>v<C-w>l
nnoremap <M-h> <C-w>h
nnoremap <M-j> <C-w>j
nnoremap <M-k> <C-w>k
nnoremap <M-l> <C-w>l

" Go to tag
nnoremap <leader>f <C-]>

" Remove trailing whitespace from all lines in file
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" Reformat paragraph
nnoremap <leader>q gqip

" Select just pasted section in visual mode
nnoremap <leader><leader>k V`]

"" Edit and reload .vimrc
nnoremap <leader>ev <C-w><C-s><C-l>:e $MYVIMRC<cr>
nnoremap <leader>sv :so $MYVIMRC<cr>

" NERDTree
nnoremap <leader><tab> :NERDTreeToggle<cr>
let NERDTreeIgnore=['.vim$', '\~$', '.*\.pyc$', 'pip-log\.txt$']
let NERDTreeDirArrows=1

" Close buffer without closing window (using bufkill)
nnoremap <leader>k :BD<cr>

" Fuzzy matching key bindings
nmap <leader>o :FufFile<cr>
nmap <leader>O :FufFile **/<cr>
nmap <leader>d :FufBuffer<cr>

" Tag list
nnoremap <leader>t :TlistToggle<cr>

" Yankring
nnoremap <silent> <leader>Y :YRShow<cr>

" VimClojure setup
let vimclojure#WantNailgun = 1
let g:vimclojure#ParenRainbow = 1

" Sudo to write
cmap w!! w !sudo tee % >/dev/null

let g:neocomplcache_enable_at_startup = 1

" Setup Haskell mode
au Bufenter *.hs compiler ghcmod_check
au Bufenter *.ghci compiler ghcmod_check

" Source a local configuration file if available.
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
