filetype off
call pathogen#runtime_append_all_bundles()
filetype plugin indent on

colorscheme neverland2

" Vim 7.3-specific options
" These options are available only in Vim 7.3
if v:version >= 730
    set relativenumber
    set undofile
    set colorcolumn=85
endif

syntax on

set vb
set t_vb=.
set nocompatible
set modelines=0
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmode=list:longest
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2

set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
set wrap
set textwidth=79
set formatoptions=qrn1

set spell

let mapleader = ","

nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

let Tlist_Use_Right_Window=1
let Tlist_WinWidth=55
set list
set listchars=tab:.\ ,eol:¬

au FocusLost * :wa

inoremap jj <ESC>

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk
nnoremap <C-J> <C-D>
nnoremap <C-K> <C-U>
inoremap <C-J> <C-D>
inoremap <C-K> <C-U>

" Movement between windows
nnoremap <leader>w <C-w>v<C-w>l
nnoremap <M-h> <C-w>h
nnoremap <M-j> <C-w>j
nnoremap <M-k> <C-w>k
nnoremap <M-l> <C-w>l

" Go to tag
nnoremap <leader>f <C-]>

" Remove trailing whitespace from all lines in file
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" Reformat paragraph
nnoremap <leader>q gqip

" Select just pasted section in visual mode
nnoremap <leader><leader>k V`]

"" Edit and reload .vimrc
nnoremap <leader>ev <C-w><C-s><C-l>:e $MYVIMRC<cr>
nnoremap <leader>sv :so $MYVIMRC<cr>

" NERDTree
nnoremap <leader><tab> :NERDTreeToggle<cr>
let NERDTreeIgnore=['.vim$', '\~$', '.*\.pyc$', 'pip-log\.txt$']

" Close buffer without closing window (using bufkill)
nnoremap <leader>k :BD<cr>

" Fuzzy matching key bindings
nmap <leader>o :FufFile<cr>
nmap <leader>O :FufFile **/<cr>
nmap <leader>d :FufBuffer<cr>

" Find word under cursor
nmap <leader>s :execute "vimgrep /" . expand("<cword>") . "/j **/*.<CR>"

" Tag list
nnoremap <leader>t :TlistToggle<cr>

" Yankring
nnoremap <silent> <leader>Y :YRShow<cr>

" Rainbows!
call rainbow_parenthsis#LoadBraces ()
call rainbow_parenthsis#LoadSquare ()
call rainbow_parenthsis#LoadRound ()
call rainbow_parenthsis#LoadChevrons ()
call rainbow_parenthsis#Activate ()
nmap <leader>R :RainbowParenthesesToggle<CR>

" Sudo to write
cmap w!! w !sudo tee % >/dev/null

" Update ctags for C++
noremap <leader>ut :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

" Setup Haskell mode
let g:haddock_browser = "open"
let g:haddock_browser_callformat = "%s %s"
au Bufenter *.hs compiler ghc
au Bufenter *.ghci compiler ghc

" Source a local configuration file if available.
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
